export const LOAD_UF_INIT = 'LOAD_UF_INIT';
export const LOAD_UF_LIST = 'LOAD_UF_LIST';
export const LOAD_UFLIST_SUCCESS = 'LOAD_UFLIST_SUCCESS';
export const LOAD_UFLIST_FAIL = 'LOAD_UFLIST_FAIL';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';

export const FETCH_WEATHER_INIT = 'FETCH_WEATHER_INIT';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL';
