export const LOAD_UF_LIST = 'LOAD_UF_LIST';
export const LOAD_UFLIST_SUCCESS = 'LOAD_UFLIST_SUCCESS';
export const LOAD_UFLIST_FAIL = 'LOAD_UFLIST_FAIL';

export const UPDATE_LOCATION = 'UPDATE_LOCATION';
